version: '3'

services:
  redis-sentinel-1:
    image: 'redis:v1'
    container_name: redis-sentinel-1
    ports:
      - 26379:26379
    command: redis-sentinel /usr/local/etc/redis/sentinel01.conf
    volumes:
      - /home/lighthouse/server/sentinel/conf:/usr/local/etc/redis
      - /home/lighthouse/server/sentinel/data:/data

networks:
  default:
    external:
      name: redis_default
