version: '3'

services:
  web_sql:
    image: 'web_mysql:v1'
    container_name: web_server
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=7788abcd!
      - MYSQL_DATABASE=flask_demo          # 创建一个默认数据库
      - MYSQL_USER=yyy                  # 创建一个普通用户
      - MYSQL_PASSWORD=8899!@cd00        # 设置普通用户的密码
    volumes:
      - /home/lighthouse/server/web/mysql_data:/var/lib/mysql
      - /home/lighthouse/server/web/flaskDemo:/app
    entrypoint: ["/entrypoint.sh"]
    # command: bash


networks:
  default:
    external:
      name: redis_default
